/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin.
 */
package org.apache.camel.salesforce.dto;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.processing.Generated;

import org.apache.camel.component.salesforce.api.dto.AbstractDescribedSObjectBase;
import org.apache.camel.component.salesforce.api.dto.Attributes;
import org.apache.camel.component.salesforce.api.dto.ChildRelationShip;
import org.apache.camel.component.salesforce.api.dto.InfoUrls;
import org.apache.camel.component.salesforce.api.dto.NamedLayoutInfo;
import org.apache.camel.component.salesforce.api.dto.RecordTypeInfo;
import org.apache.camel.component.salesforce.api.dto.SObjectDescription;
import org.apache.camel.component.salesforce.api.dto.SObjectDescriptionUrls;
import org.apache.camel.component.salesforce.api.dto.SObjectField;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.databind.annotation.JsonTypeResolver;
import org.apache.camel.component.salesforce.api.utils.AsNestedPropertyResolver;

/**
 * Salesforce DTO for SObject Lead
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public class Lead extends AbstractDescribedSObjectBase {

    public Lead() {
        getAttributes().setType("Lead");
    }

    private static final SObjectDescription DESCRIPTION = createSObjectDescription();

    private String MasterRecordId;

    @JsonProperty("MasterRecordId")
    public String getMasterRecordId() {
        return this.MasterRecordId;
    }

    @JsonProperty("MasterRecordId")
    public void setMasterRecordId(String MasterRecordId) {
        this.MasterRecordId = MasterRecordId;
    }

    private Lead MasterRecord;

    @JsonProperty("MasterRecord")
    public Lead getMasterRecord() {
        return this.MasterRecord;
    }

    @JsonProperty("MasterRecord")
    public void setMasterRecord(Lead MasterRecord) {
        this.MasterRecord = MasterRecord;
    }
    private String LastName;

    @JsonProperty("LastName")
    public String getLastName() {
        return this.LastName;
    }

    @JsonProperty("LastName")
    public void setLastName(String LastName) {
        this.LastName = LastName;
    }

    private String FirstName;

    @JsonProperty("FirstName")
    public String getFirstName() {
        return this.FirstName;
    }

    @JsonProperty("FirstName")
    public void setFirstName(String FirstName) {
        this.FirstName = FirstName;
    }

    private Lead_SalutationEnum Salutation;

    @JsonProperty("Salutation")
    public Lead_SalutationEnum getSalutation() {
        return this.Salutation;
    }

    @JsonProperty("Salutation")
    public void setSalutation(Lead_SalutationEnum Salutation) {
        this.Salutation = Salutation;
    }

    private String Title;

    @JsonProperty("Title")
    public String getTitle() {
        return this.Title;
    }

    @JsonProperty("Title")
    public void setTitle(String Title) {
        this.Title = Title;
    }

    private String Company;

    @JsonProperty("Company")
    public String getCompany() {
        return this.Company;
    }

    @JsonProperty("Company")
    public void setCompany(String Company) {
        this.Company = Company;
    }

    private String Street;

    @JsonProperty("Street")
    public String getStreet() {
        return this.Street;
    }

    @JsonProperty("Street")
    public void setStreet(String Street) {
        this.Street = Street;
    }

    private String City;

    @JsonProperty("City")
    public String getCity() {
        return this.City;
    }

    @JsonProperty("City")
    public void setCity(String City) {
        this.City = City;
    }

    private String State;

    @JsonProperty("State")
    public String getState() {
        return this.State;
    }

    @JsonProperty("State")
    public void setState(String State) {
        this.State = State;
    }

    private String PostalCode;

    @JsonProperty("PostalCode")
    public String getPostalCode() {
        return this.PostalCode;
    }

    @JsonProperty("PostalCode")
    public void setPostalCode(String PostalCode) {
        this.PostalCode = PostalCode;
    }

    private String Country;

    @JsonProperty("Country")
    public String getCountry() {
        return this.Country;
    }

    @JsonProperty("Country")
    public void setCountry(String Country) {
        this.Country = Country;
    }

    private Double Latitude;

    @JsonProperty("Latitude")
    public Double getLatitude() {
        return this.Latitude;
    }

    @JsonProperty("Latitude")
    public void setLatitude(Double Latitude) {
        this.Latitude = Latitude;
    }

    private Double Longitude;

    @JsonProperty("Longitude")
    public Double getLongitude() {
        return this.Longitude;
    }

    @JsonProperty("Longitude")
    public void setLongitude(Double Longitude) {
        this.Longitude = Longitude;
    }

    private Lead_GeocodeAccuracyEnum GeocodeAccuracy;

    @JsonProperty("GeocodeAccuracy")
    public Lead_GeocodeAccuracyEnum getGeocodeAccuracy() {
        return this.GeocodeAccuracy;
    }

    @JsonProperty("GeocodeAccuracy")
    public void setGeocodeAccuracy(Lead_GeocodeAccuracyEnum GeocodeAccuracy) {
        this.GeocodeAccuracy = GeocodeAccuracy;
    }

    private org.apache.camel.component.salesforce.api.dto.Address Address;

    @JsonProperty("Address")
    public org.apache.camel.component.salesforce.api.dto.Address getAddress() {
        return this.Address;
    }

    @JsonProperty("Address")
    public void setAddress(org.apache.camel.component.salesforce.api.dto.Address Address) {
        this.Address = Address;
    }

    private String Phone;

    @JsonProperty("Phone")
    public String getPhone() {
        return this.Phone;
    }

    @JsonProperty("Phone")
    public void setPhone(String Phone) {
        this.Phone = Phone;
    }

    private String MobilePhone;

    @JsonProperty("MobilePhone")
    public String getMobilePhone() {
        return this.MobilePhone;
    }

    @JsonProperty("MobilePhone")
    public void setMobilePhone(String MobilePhone) {
        this.MobilePhone = MobilePhone;
    }

    private String Fax;

    @JsonProperty("Fax")
    public String getFax() {
        return this.Fax;
    }

    @JsonProperty("Fax")
    public void setFax(String Fax) {
        this.Fax = Fax;
    }

    private String Email;

    @JsonProperty("Email")
    public String getEmail() {
        return this.Email;
    }

    @JsonProperty("Email")
    public void setEmail(String Email) {
        this.Email = Email;
    }

    private String Website;

    @JsonProperty("Website")
    public String getWebsite() {
        return this.Website;
    }

    @JsonProperty("Website")
    public void setWebsite(String Website) {
        this.Website = Website;
    }

    private String PhotoUrl;

    @JsonProperty("PhotoUrl")
    public String getPhotoUrl() {
        return this.PhotoUrl;
    }

    @JsonProperty("PhotoUrl")
    public void setPhotoUrl(String PhotoUrl) {
        this.PhotoUrl = PhotoUrl;
    }

    private String Description;

    @JsonProperty("Description")
    public String getDescription() {
        return this.Description;
    }

    @JsonProperty("Description")
    public void setDescription(String Description) {
        this.Description = Description;
    }

    private Lead_LeadSourceEnum LeadSource;

    @JsonProperty("LeadSource")
    public Lead_LeadSourceEnum getLeadSource() {
        return this.LeadSource;
    }

    @JsonProperty("LeadSource")
    public void setLeadSource(Lead_LeadSourceEnum LeadSource) {
        this.LeadSource = LeadSource;
    }

    private Lead_StatusEnum Status;

    @JsonProperty("Status")
    public Lead_StatusEnum getStatus() {
        return this.Status;
    }

    @JsonProperty("Status")
    public void setStatus(Lead_StatusEnum Status) {
        this.Status = Status;
    }

    private Lead_IndustryEnum Industry;

    @JsonProperty("Industry")
    public Lead_IndustryEnum getIndustry() {
        return this.Industry;
    }

    @JsonProperty("Industry")
    public void setIndustry(Lead_IndustryEnum Industry) {
        this.Industry = Industry;
    }

    private Lead_RatingEnum Rating;

    @JsonProperty("Rating")
    public Lead_RatingEnum getRating() {
        return this.Rating;
    }

    @JsonProperty("Rating")
    public void setRating(Lead_RatingEnum Rating) {
        this.Rating = Rating;
    }

    private Double AnnualRevenue;

    @JsonProperty("AnnualRevenue")
    public Double getAnnualRevenue() {
        return this.AnnualRevenue;
    }

    @JsonProperty("AnnualRevenue")
    public void setAnnualRevenue(Double AnnualRevenue) {
        this.AnnualRevenue = AnnualRevenue;
    }

    private Integer NumberOfEmployees;

    @JsonProperty("NumberOfEmployees")
    public Integer getNumberOfEmployees() {
        return this.NumberOfEmployees;
    }

    @JsonProperty("NumberOfEmployees")
    public void setNumberOfEmployees(Integer NumberOfEmployees) {
        this.NumberOfEmployees = NumberOfEmployees;
    }

    @JsonTypeResolver(AsNestedPropertyResolver.class)
    @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "attributes.type",
        defaultImpl = AbstractDescribedSObjectBase.class)
    @JsonSubTypes({
    })
    private AbstractDescribedSObjectBase Owner;

    @JsonProperty("Owner")
    public AbstractDescribedSObjectBase getOwner() {
        return this.Owner;
    }

    @JsonProperty("Owner")
    public void setOwner(AbstractDescribedSObjectBase Owner) {
        this.Owner = Owner;
    }
    private Boolean IsConverted;

    @JsonProperty("IsConverted")
    public Boolean getIsConverted() {
        return this.IsConverted;
    }

    @JsonProperty("IsConverted")
    public void setIsConverted(Boolean IsConverted) {
        this.IsConverted = IsConverted;
    }

    private java.time.LocalDate ConvertedDate;

    @JsonProperty("ConvertedDate")
    public java.time.LocalDate getConvertedDate() {
        return this.ConvertedDate;
    }

    @JsonProperty("ConvertedDate")
    public void setConvertedDate(java.time.LocalDate ConvertedDate) {
        this.ConvertedDate = ConvertedDate;
    }

    private String ConvertedAccountId;

    @JsonProperty("ConvertedAccountId")
    public String getConvertedAccountId() {
        return this.ConvertedAccountId;
    }

    @JsonProperty("ConvertedAccountId")
    public void setConvertedAccountId(String ConvertedAccountId) {
        this.ConvertedAccountId = ConvertedAccountId;
    }

    private AbstractDescribedSObjectBase ConvertedAccount;

    @JsonProperty("ConvertedAccount")
    public AbstractDescribedSObjectBase getConvertedAccount() {
        return this.ConvertedAccount;
    }

    @JsonProperty("ConvertedAccount")
    public void setConvertedAccount(AbstractDescribedSObjectBase ConvertedAccount) {
        this.ConvertedAccount = ConvertedAccount;
    }
    private String ConvertedContactId;

    @JsonProperty("ConvertedContactId")
    public String getConvertedContactId() {
        return this.ConvertedContactId;
    }

    @JsonProperty("ConvertedContactId")
    public void setConvertedContactId(String ConvertedContactId) {
        this.ConvertedContactId = ConvertedContactId;
    }

    private AbstractDescribedSObjectBase ConvertedContact;

    @JsonProperty("ConvertedContact")
    public AbstractDescribedSObjectBase getConvertedContact() {
        return this.ConvertedContact;
    }

    @JsonProperty("ConvertedContact")
    public void setConvertedContact(AbstractDescribedSObjectBase ConvertedContact) {
        this.ConvertedContact = ConvertedContact;
    }
    private String ConvertedOpportunityId;

    @JsonProperty("ConvertedOpportunityId")
    public String getConvertedOpportunityId() {
        return this.ConvertedOpportunityId;
    }

    @JsonProperty("ConvertedOpportunityId")
    public void setConvertedOpportunityId(String ConvertedOpportunityId) {
        this.ConvertedOpportunityId = ConvertedOpportunityId;
    }

    private AbstractDescribedSObjectBase ConvertedOpportunity;

    @JsonProperty("ConvertedOpportunity")
    public AbstractDescribedSObjectBase getConvertedOpportunity() {
        return this.ConvertedOpportunity;
    }

    @JsonProperty("ConvertedOpportunity")
    public void setConvertedOpportunity(AbstractDescribedSObjectBase ConvertedOpportunity) {
        this.ConvertedOpportunity = ConvertedOpportunity;
    }
    private Boolean IsUnreadByOwner;

    @JsonProperty("IsUnreadByOwner")
    public Boolean getIsUnreadByOwner() {
        return this.IsUnreadByOwner;
    }

    @JsonProperty("IsUnreadByOwner")
    public void setIsUnreadByOwner(Boolean IsUnreadByOwner) {
        this.IsUnreadByOwner = IsUnreadByOwner;
    }

    private AbstractDescribedSObjectBase CreatedBy;

    @JsonProperty("CreatedBy")
    public AbstractDescribedSObjectBase getCreatedBy() {
        return this.CreatedBy;
    }

    @JsonProperty("CreatedBy")
    public void setCreatedBy(AbstractDescribedSObjectBase CreatedBy) {
        this.CreatedBy = CreatedBy;
    }
    private AbstractDescribedSObjectBase LastModifiedBy;

    @JsonProperty("LastModifiedBy")
    public AbstractDescribedSObjectBase getLastModifiedBy() {
        return this.LastModifiedBy;
    }

    @JsonProperty("LastModifiedBy")
    public void setLastModifiedBy(AbstractDescribedSObjectBase LastModifiedBy) {
        this.LastModifiedBy = LastModifiedBy;
    }
    private String Jigsaw;

    @JsonProperty("Jigsaw")
    public String getJigsaw() {
        return this.Jigsaw;
    }

    @JsonProperty("Jigsaw")
    public void setJigsaw(String Jigsaw) {
        this.Jigsaw = Jigsaw;
    }

    private String JigsawContactId;

    @JsonProperty("JigsawContactId")
    public String getJigsawContactId() {
        return this.JigsawContactId;
    }

    @JsonProperty("JigsawContactId")
    public void setJigsawContactId(String JigsawContactId) {
        this.JigsawContactId = JigsawContactId;
    }

    private Lead_CleanStatusEnum CleanStatus;

    @JsonProperty("CleanStatus")
    public Lead_CleanStatusEnum getCleanStatus() {
        return this.CleanStatus;
    }

    @JsonProperty("CleanStatus")
    public void setCleanStatus(Lead_CleanStatusEnum CleanStatus) {
        this.CleanStatus = CleanStatus;
    }

    private String CompanyDunsNumber;

    @JsonProperty("CompanyDunsNumber")
    public String getCompanyDunsNumber() {
        return this.CompanyDunsNumber;
    }

    @JsonProperty("CompanyDunsNumber")
    public void setCompanyDunsNumber(String CompanyDunsNumber) {
        this.CompanyDunsNumber = CompanyDunsNumber;
    }

    private String DandbCompanyId;

    @JsonProperty("DandbCompanyId")
    public String getDandbCompanyId() {
        return this.DandbCompanyId;
    }

    @JsonProperty("DandbCompanyId")
    public void setDandbCompanyId(String DandbCompanyId) {
        this.DandbCompanyId = DandbCompanyId;
    }

    private AbstractDescribedSObjectBase DandbCompany;

    @JsonProperty("DandbCompany")
    public AbstractDescribedSObjectBase getDandbCompany() {
        return this.DandbCompany;
    }

    @JsonProperty("DandbCompany")
    public void setDandbCompany(AbstractDescribedSObjectBase DandbCompany) {
        this.DandbCompany = DandbCompany;
    }
    private String EmailBouncedReason;

    @JsonProperty("EmailBouncedReason")
    public String getEmailBouncedReason() {
        return this.EmailBouncedReason;
    }

    @JsonProperty("EmailBouncedReason")
    public void setEmailBouncedReason(String EmailBouncedReason) {
        this.EmailBouncedReason = EmailBouncedReason;
    }

    private java.time.ZonedDateTime EmailBouncedDate;

    @JsonProperty("EmailBouncedDate")
    public java.time.ZonedDateTime getEmailBouncedDate() {
        return this.EmailBouncedDate;
    }

    @JsonProperty("EmailBouncedDate")
    public void setEmailBouncedDate(java.time.ZonedDateTime EmailBouncedDate) {
        this.EmailBouncedDate = EmailBouncedDate;
    }

    private String IndividualId;

    @JsonProperty("IndividualId")
    public String getIndividualId() {
        return this.IndividualId;
    }

    @JsonProperty("IndividualId")
    public void setIndividualId(String IndividualId) {
        this.IndividualId = IndividualId;
    }

    private AbstractDescribedSObjectBase Individual;

    @JsonProperty("Individual")
    public AbstractDescribedSObjectBase getIndividual() {
        return this.Individual;
    }

    @JsonProperty("Individual")
    public void setIndividual(AbstractDescribedSObjectBase Individual) {
        this.Individual = Individual;
    }
    private String SICCode__c;

    @JsonProperty("SICCode__c")
    public String getSICCode__c() {
        return this.SICCode__c;
    }

    @JsonProperty("SICCode__c")
    public void setSICCode__c(String SICCode__c) {
        this.SICCode__c = SICCode__c;
    }

    private Lead_ProductInterestEnum ProductInterest__c;

    @JsonProperty("ProductInterest__c")
    public Lead_ProductInterestEnum getProductInterest__c() {
        return this.ProductInterest__c;
    }

    @JsonProperty("ProductInterest__c")
    public void setProductInterest__c(Lead_ProductInterestEnum ProductInterest__c) {
        this.ProductInterest__c = ProductInterest__c;
    }

    private Lead_PrimaryEnum Primary__c;

    @JsonProperty("Primary__c")
    public Lead_PrimaryEnum getPrimary__c() {
        return this.Primary__c;
    }

    @JsonProperty("Primary__c")
    public void setPrimary__c(Lead_PrimaryEnum Primary__c) {
        this.Primary__c = Primary__c;
    }

    private String CurrentGenerators__c;

    @JsonProperty("CurrentGenerators__c")
    public String getCurrentGenerators__c() {
        return this.CurrentGenerators__c;
    }

    @JsonProperty("CurrentGenerators__c")
    public void setCurrentGenerators__c(String CurrentGenerators__c) {
        this.CurrentGenerators__c = CurrentGenerators__c;
    }

    private Double NumberofLocations__c;

    @JsonProperty("NumberofLocations__c")
    public Double getNumberofLocations__c() {
        return this.NumberofLocations__c;
    }

    @JsonProperty("NumberofLocations__c")
    public void setNumberofLocations__c(Double NumberofLocations__c) {
        this.NumberofLocations__c = NumberofLocations__c;
    }


    @Override
    public final SObjectDescription description() {
        return DESCRIPTION;
    }

    private static SObjectDescription createSObjectDescription() {
        final SObjectDescription description = new SObjectDescription();



        final List<SObjectField> fields1 = new ArrayList<>();
        description.setFields(fields1);

        final SObjectField sObjectField1 = createField("Id", "Lead ID", "id", "tns:ID", 18, false, false, false, false, false, false, true);
        fields1.add(sObjectField1);
        final SObjectField sObjectField2 = createField("IsDeleted", "Deleted", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField2);
        final SObjectField sObjectField3 = createField("MasterRecordId", "Master Record ID", "reference", "tns:ID", 18, false, true, false, false, false, false, false);
        fields1.add(sObjectField3);
        final SObjectField sObjectField4 = createField("LastName", "Last Name", "string", "xsd:string", 80, false, false, false, false, false, false, false);
        fields1.add(sObjectField4);
        final SObjectField sObjectField5 = createField("FirstName", "First Name", "string", "xsd:string", 40, false, true, false, false, false, false, false);
        fields1.add(sObjectField5);
        final SObjectField sObjectField6 = createField("Salutation", "Salutation", "picklist", "xsd:string", 40, false, true, false, false, false, false, false);
        fields1.add(sObjectField6);
        final SObjectField sObjectField7 = createField("Name", "Full Name", "string", "xsd:string", 121, false, false, true, false, false, false, false);
        fields1.add(sObjectField7);
        final SObjectField sObjectField8 = createField("Title", "Title", "string", "xsd:string", 128, false, true, false, false, false, false, false);
        fields1.add(sObjectField8);
        final SObjectField sObjectField9 = createField("Company", "Company", "string", "xsd:string", 255, false, false, false, false, false, false, false);
        fields1.add(sObjectField9);
        final SObjectField sObjectField10 = createField("Street", "Street", "textarea", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField10);
        final SObjectField sObjectField11 = createField("City", "City", "string", "xsd:string", 40, false, true, false, false, false, false, false);
        fields1.add(sObjectField11);
        final SObjectField sObjectField12 = createField("State", "State/Province", "string", "xsd:string", 80, false, true, false, false, false, false, false);
        fields1.add(sObjectField12);
        final SObjectField sObjectField13 = createField("PostalCode", "Zip/Postal Code", "string", "xsd:string", 20, false, true, false, false, false, false, false);
        fields1.add(sObjectField13);
        final SObjectField sObjectField14 = createField("Country", "Country", "string", "xsd:string", 80, false, true, false, false, false, false, false);
        fields1.add(sObjectField14);
        final SObjectField sObjectField15 = createField("Latitude", "Latitude", "double", "xsd:double", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField15);
        final SObjectField sObjectField16 = createField("Longitude", "Longitude", "double", "xsd:double", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField16);
        final SObjectField sObjectField17 = createField("GeocodeAccuracy", "Geocode Accuracy", "picklist", "xsd:string", 40, false, true, false, false, false, false, false);
        fields1.add(sObjectField17);
        final SObjectField sObjectField18 = createField("Address", "Address", "address", "urn:address", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField18);
        final SObjectField sObjectField19 = createField("Phone", "Phone", "phone", "xsd:string", 40, false, true, false, false, false, false, false);
        fields1.add(sObjectField19);
        final SObjectField sObjectField20 = createField("MobilePhone", "Mobile Phone", "phone", "xsd:string", 40, false, true, false, false, false, false, false);
        fields1.add(sObjectField20);
        final SObjectField sObjectField21 = createField("Fax", "Fax", "phone", "xsd:string", 40, false, true, false, false, false, false, false);
        fields1.add(sObjectField21);
        final SObjectField sObjectField22 = createField("Email", "Email", "email", "xsd:string", 80, false, true, false, false, false, false, true);
        fields1.add(sObjectField22);
        final SObjectField sObjectField23 = createField("Website", "Website", "url", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField23);
        final SObjectField sObjectField24 = createField("PhotoUrl", "Photo URL", "url", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField24);
        final SObjectField sObjectField25 = createField("Description", "Description", "textarea", "xsd:string", 32000, false, true, false, false, false, false, false);
        fields1.add(sObjectField25);
        final SObjectField sObjectField26 = createField("LeadSource", "Lead Source", "picklist", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField26);
        final SObjectField sObjectField27 = createField("Status", "Status", "picklist", "xsd:string", 255, false, false, false, false, false, false, false);
        fields1.add(sObjectField27);
        final SObjectField sObjectField28 = createField("Industry", "Industry", "picklist", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField28);
        final SObjectField sObjectField29 = createField("Rating", "Rating", "picklist", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField29);
        final SObjectField sObjectField30 = createField("AnnualRevenue", "Annual Revenue", "currency", "xsd:double", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField30);
        final SObjectField sObjectField31 = createField("NumberOfEmployees", "Employees", "int", "xsd:int", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField31);
        final SObjectField sObjectField32 = createField("OwnerId", "Owner ID", "reference", "tns:ID", 18, false, false, false, false, false, false, false);
        fields1.add(sObjectField32);
        final SObjectField sObjectField33 = createField("IsConverted", "Converted", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField33);
        final SObjectField sObjectField34 = createField("ConvertedDate", "Converted Date", "date", "xsd:date", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField34);
        final SObjectField sObjectField35 = createField("ConvertedAccountId", "Converted Account ID", "reference", "tns:ID", 18, false, true, false, false, false, false, false);
        fields1.add(sObjectField35);
        final SObjectField sObjectField36 = createField("ConvertedContactId", "Converted Contact ID", "reference", "tns:ID", 18, false, true, false, false, false, false, false);
        fields1.add(sObjectField36);
        final SObjectField sObjectField37 = createField("ConvertedOpportunityId", "Converted Opportunity ID", "reference", "tns:ID", 18, false, true, false, false, false, false, false);
        fields1.add(sObjectField37);
        final SObjectField sObjectField38 = createField("IsUnreadByOwner", "Unread By Owner", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField38);
        final SObjectField sObjectField39 = createField("CreatedDate", "Created Date", "datetime", "xsd:dateTime", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField39);
        final SObjectField sObjectField40 = createField("CreatedById", "Created By ID", "reference", "tns:ID", 18, false, false, false, false, false, false, false);
        fields1.add(sObjectField40);
        final SObjectField sObjectField41 = createField("LastModifiedDate", "Last Modified Date", "datetime", "xsd:dateTime", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField41);
        final SObjectField sObjectField42 = createField("LastModifiedById", "Last Modified By ID", "reference", "tns:ID", 18, false, false, false, false, false, false, false);
        fields1.add(sObjectField42);
        final SObjectField sObjectField43 = createField("SystemModstamp", "System Modstamp", "datetime", "xsd:dateTime", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField43);
        final SObjectField sObjectField44 = createField("LastActivityDate", "Last Activity", "date", "xsd:date", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField44);
        final SObjectField sObjectField45 = createField("LastViewedDate", "Last Viewed Date", "datetime", "xsd:dateTime", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField45);
        final SObjectField sObjectField46 = createField("LastReferencedDate", "Last Referenced Date", "datetime", "xsd:dateTime", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField46);
        final SObjectField sObjectField47 = createField("Jigsaw", "Data.com Key", "string", "xsd:string", 20, false, true, false, false, false, false, false);
        fields1.add(sObjectField47);
        final SObjectField sObjectField48 = createField("JigsawContactId", "Jigsaw Contact ID", "string", "xsd:string", 20, false, true, false, false, false, false, false);
        fields1.add(sObjectField48);
        final SObjectField sObjectField49 = createField("CleanStatus", "Clean Status", "picklist", "xsd:string", 40, false, true, false, false, false, false, false);
        fields1.add(sObjectField49);
        final SObjectField sObjectField50 = createField("CompanyDunsNumber", "Company D-U-N-S Number", "string", "xsd:string", 9, false, true, false, false, false, false, false);
        fields1.add(sObjectField50);
        final SObjectField sObjectField51 = createField("DandbCompanyId", "D&B Company ID", "reference", "tns:ID", 18, false, true, false, false, false, false, false);
        fields1.add(sObjectField51);
        final SObjectField sObjectField52 = createField("EmailBouncedReason", "Email Bounced Reason", "string", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField52);
        final SObjectField sObjectField53 = createField("EmailBouncedDate", "Email Bounced Date", "datetime", "xsd:dateTime", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField53);
        final SObjectField sObjectField54 = createField("IndividualId", "Individual ID", "reference", "tns:ID", 18, false, true, false, false, false, false, false);
        fields1.add(sObjectField54);
        final SObjectField sObjectField55 = createField("SICCode__c", "SIC Code", "string", "xsd:string", 15, false, true, false, false, true, false, false);
        fields1.add(sObjectField55);
        final SObjectField sObjectField56 = createField("ProductInterest__c", "Product Interest", "picklist", "xsd:string", 255, false, true, false, false, true, false, false);
        fields1.add(sObjectField56);
        final SObjectField sObjectField57 = createField("Primary__c", "Primary", "picklist", "xsd:string", 255, false, true, false, false, true, false, false);
        fields1.add(sObjectField57);
        final SObjectField sObjectField58 = createField("CurrentGenerators__c", "Current Generator(s)", "string", "xsd:string", 100, false, true, false, false, true, false, false);
        fields1.add(sObjectField58);
        final SObjectField sObjectField59 = createField("NumberofLocations__c", "Number of Locations", "double", "xsd:double", 0, false, true, false, false, true, false, false);
        fields1.add(sObjectField59);

        description.setLabel("Lead");
        description.setLabelPlural("Leads");
        description.setName("Lead");

        final SObjectDescriptionUrls sObjectDescriptionUrls1 = new SObjectDescriptionUrls();
        sObjectDescriptionUrls1.setApprovalLayouts("/services/data/v56.0/sobjects/Lead/describe/approvalLayouts");
        sObjectDescriptionUrls1.setCompactLayouts("/services/data/v56.0/sobjects/Lead/describe/compactLayouts");
        sObjectDescriptionUrls1.setDescribe("/services/data/v56.0/sobjects/Lead/describe");
        sObjectDescriptionUrls1.setLayouts("/services/data/v56.0/sobjects/Lead/describe/layouts");
        sObjectDescriptionUrls1.setListviews("/services/data/v56.0/sobjects/Lead/listviews");
        sObjectDescriptionUrls1.setQuickActions("/services/data/v56.0/sobjects/Lead/quickActions");
        sObjectDescriptionUrls1.setRowTemplate("/services/data/v56.0/sobjects/Lead/{ID}");
        sObjectDescriptionUrls1.setSobject("/services/data/v56.0/sobjects/Lead");
        sObjectDescriptionUrls1.setUiDetailTemplate("https://d3i000000dbpjeao-dev-ed.my.salesforce.com/{ID}");
        sObjectDescriptionUrls1.setUiEditTemplate("https://d3i000000dbpjeao-dev-ed.my.salesforce.com/{ID}/e");
        sObjectDescriptionUrls1.setUiNewRecord("https://d3i000000dbpjeao-dev-ed.my.salesforce.com/00Q/e");
        description.setUrls(sObjectDescriptionUrls1);

        return description;
    }
}
