/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 */
package org.apache.camel.salesforce.dto;

import javax.annotation.processing.Generated;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Primary__c
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum Lead_PrimaryEnum {

    // No
    NO("No"),

    // Yes
    YES("Yes");

    final String value;

    private Lead_PrimaryEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Lead_PrimaryEnum fromValue(String value) {
        for (Lead_PrimaryEnum e : Lead_PrimaryEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }
}
