/*
 * Salesforce Query DTO generated by camel-salesforce-maven-plugin
 */
package org.apache.camel.salesforce.dto;

import org.apache.camel.component.salesforce.api.dto.AbstractQueryRecordsBase;

import java.util.List;
import javax.annotation.processing.Generated;

/**
 * Salesforce QueryRecords DTO for type Lead
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public class QueryRecordsLead extends AbstractQueryRecordsBase<Lead> {
}
